name: Rebase Dev with Master

on:
  push:
    branches:
      - main

jobs:
  rebase_dev:
    runs-on: ubuntu-latest
    name: RebaseDev

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Fetch all branches
      run: git fetch --all

    - name: Rebase dev with main
      run: |
        git checkout main
        git pull origin main
        git checkout dev
        git rebase main
        git push origin dev
